### ISSUE TITLE
서버 배포

### ISSUE THREAD

**Issue by zych1751** [webdonalds/YAS-backend#35]
도메인은 나중에 사더라도 그냥 ip주소로라도 배포해봅시당
 - nginx
 - server/client 도커로 말아올리기

**Comment by hellodhlyn** [comment]
webdonalds.org 있으니까 개발 서버는 yas.webdonalds.org 같은거라도 붙혀요

**Comment by zych1751** [comment]
:+1: 
그게 있네여 붙일때 참고할게요 ^_^
